### ISSUE TITLE
Mention when pre-sale ends

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/obelisk.tech#1]
Consider making it more obvious that the pre-sale ends soon.

If the customer didn't dig into the original [Obelisk reddit thread](https://www.reddit.com/r/siacoin/comments/6j1gyg/obelisks_sia_asics_full_details/?st=j4mtohq9&sh=40c0c46f), they'd have no idea that this is a limited time offer. It's not mentioned anywhere on the sales site and it's not even mentioned anywhere on the [currently stickied post](https://www.reddit.com/r/siacoin/comments/6k3gnj/obelisk_presale_is_live/?sort=new&st=j4mtg119&sh=3fbdd4a2). I read *a lot* about Sia and I had no idea the pre-sale was only 7 days until a day or two after the sale began.

Putting a time limit on it creates a sense of urgency in the buyer. Otherwise, they have no incentive to purchase something now that won't ship for another 9-12 months.

**Comment by avahowell** [comment]
added in  226bd43
